volodymyr.bezpalchuk #4
MastersAcademy/devops-course-2020 pull request #11
Opened 2020-11-14 12:40 UTC by monferat

part 1 (Ready)

part 2 (not completely ready)

2020-11-14 13:04 UTC, MrCartoon requested changes

2020-11-14 13:04 UTC, MrCartoon commented on lesson 4/volodymyr.bezpalchuk/Ruby
> +FROM ubuntu:20.04
Краще використай COPY і додай "проект" в докер імейдж. Я не можу запустити вебсервер.
![image](https://user-images.githubusercontent.com/25508110/99147522-66626980-268a-11eb-8306-d57e0724d8b3.png)

2020-11-14 21:03 UTC, monferat commented on lesson 4/volodymyr.bezpalchuk/Ruby
> +FROM ubuntu:20.04
Поправив Ruby докерфайл і запушив новий ruby імедж у докерхаб. Але db i cache повертають error, хоча контейнери запущені (

2020-11-16 16:04 UTC, monferat commented on lesson 4/volodymyr.bezpalchuk/Ruby
> +FROM ubuntu:20.04
@MrCartoon Перезалив імеджі в докехаб і поправив докерфайли для postgres i redis, додав project.sh, тепер має працювати

2020-11-17 07:42 UTC, merged