made homework 3
MastersAcademy/devops-course-2020 pull request #12
Opened 2020-11-14 13:14 UTC by DrSmile444

Finished Homework 3

2020-11-16 10:08 UTC, MrCartoon requested changes

2020-11-16 10:08 UTC, MrCartoon commented on lesson 3/dmytro.vakulenko/project.sh
> +  --mount type=bind,source="${PROJECT_DIR}",target=/app \
краще використати `--mount "${PROJECT_DIR}":/app`

2020-11-18 13:17 UTC, DrSmile444 commented on lesson 3/dmytro.vakulenko/project.sh
> +  --mount type=bind,source="${PROJECT_DIR}",target=/app \
working on it, thank you!

2020-11-20 19:31 UTC, DrSmile444 commented on lesson 3/dmytro.vakulenko/project.sh
> +  --mount type=bind,source="${PROJECT_DIR}",target=/app \
Done! Review, please 😄

2020-11-21 22:33 UTC, MrCartoon commented on lesson 3/dmytro.vakulenko/project.sh
> +  --mount "${PROJECT_DIR}":/app \
Personally, I use `-v` (volume) instead of `--mount`.

2020-11-21 22:33 UTC, MrCartoon approved these changes

2020-11-21 22:33 UTC, merged