volodymyr.bezpalchuk #5
MastersAcademy/devops-course-2020 pull request #23
Opened 2020-11-20 17:28 UTC by monferat

2020-11-21 22:45 UTC, MrCartoon requested changes

2020-11-21 22:45 UTC, MrCartoon commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      - ./:/app
Ти можеш використати `../:` для того щоб підключити папку вищого рівня. В цьому випадку це буде папка `lesson 5`.
Тоді тобі не прийдеться дублювати `server.rb`

2020-11-21 22:45 UTC, MrCartoon commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +    container_name: ruby_server
Старайся не використовувати `container_name`. Якщо всі розробники будуть використовувати цю опцію, тоді в якийсь момент одночасно не вийде тримати декілька сервісів(проектів).
docker-compose по стандарту присваює назву сервісу як hostname. Наприклад якщо в `psql` прибрати `container_name` тоді до контейнеру постгресу все ще можна буде підключитись від `psql` аліасу.
Ми це проходили на воркшопі. Я там не додавав `container_name` а на пряму використовував стандартний аліас.

2020-11-23 17:54 UTC, monferat commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      - ./:/app
додав `context` і видалив `server.rb`

2020-11-23 17:55 UTC, monferat commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +    container_name: ruby_server
видалив `container_name` з `docker-compose.yml`

2020-11-23 19:12 UTC, MrCartoon requested changes

2020-11-23 19:12 UTC, MrCartoon commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      DB: 'postgresql://postgres:dbpass@volodymyrbezpalchuk_psql_1/postgres'
Так як контейнери знаходяться в одному docker-compose.yml достатньо `...@psql/...`.

2020-11-23 19:14 UTC, MrCartoon requested changes

2020-11-23 19:14 UTC, MrCartoon commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      context: ../
Так як в `Dockerfile` ти взагалі не використовуєш ні `ADD`, ні `COPY`, потреба в `context` відпадає.

2020-11-24 13:01 UTC, monferat commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      DB: 'postgresql://postgres:dbpass@volodymyrbezpalchuk_psql_1/postgres'
виправив на `@psql`

2020-11-24 13:02 UTC, monferat commented on lesson 5/volodymyr.bezpalchuk/docker-compose.yml
> +      context: ../
видалив `context`

2020-11-24 18:59 UTC, MrCartoon approved these changes

2020-11-24 18:59 UTC, merged