sashka.datsenko #5
MastersAcademy/devops-course-2020 pull request #24
Opened 2020-11-20 18:23 UTC by sashok-15

add homework #5

2020-11-21 22:49 UTC, MrCartoon requested changes

2020-11-21 22:49 UTC, MrCartoon commented on lesson 5/sashka.datsenko/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Треба зробити без клонування `serveer.rb`, можеш почитати про [build context](https://docs.docker.com/compose/compose-file/#context), або зробити через [volume](https://docs.docker.com/compose/compose-file/#volumes).

2020-11-22 15:46 UTC, sashok-15 commented on lesson 5/sashka.datsenko/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Зробив через context.

2020-11-23 07:29 UTC, MrCartoon approved these changes

2020-11-23 07:29 UTC, merged