alexey.boguslavets
MastersAcademy/devops-course-2020 pull request #25
Opened 2020-11-21 10:35 UTC by alexxck

hw5 done

2020-11-21 22:52 UTC, MrCartoon approved these changes, later dismissed

2020-11-21 22:52 UTC, MrCartoon commented on lesson 5/alexey.boguslavets/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Треба зробити без клонування `server.rb`, можеш почитати про [build context](https://docs.docker.com/compose/compose-file/#context), або зробити через [volume](https://docs.docker.com/compose/compose-file/#volumes).

2020-11-21 22:52 UTC, MrCartoon commented on lesson 5/alexey.boguslavets/docker-compose.yml
> +    container_name: ruby
Старайся використовувати `container_name` якомога рідше, бо воно не дозволить потім створювати інші контейнери з такою ж назвою. Треба виправити.

2020-11-21 22:53 UTC, MrCartoon requested changes
Треба зробити виправлення.

2020-11-22 17:34 UTC, alexxck commented
сейчас правильно?

2020-11-23 07:36 UTC, MrCartoon commented
Ні, треба видалити `server.rb` в твоїй папці і зробити без нього.

2020-11-23 11:33 UTC, MrCartoon approved these changes

2020-11-23 11:33 UTC, merged