Lesson 5
MastersAcademy/devops-course-2020 pull request #32
Opened 2020-11-23 20:34 UTC by Karavan89

2020-11-23 21:27 UTC, MrCartoon requested changes

2020-11-23 21:27 UTC, MrCartoon commented on lesson 5/serhii.karavan/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Треба зробити без клонування `server.rb`, можеш почитати про [build context](https://docs.docker.com/compose/compose-file/#context), або зробити через [volume](https://docs.docker.com/compose/compose-file/#volumes).

2020-11-23 21:27 UTC, MrCartoon commented on lesson 5/serhii.karavan/docker-compose.yml
> +  Postgres:
Назви прийнято писати з маленької букви.

2020-11-23 21:27 UTC, MrCartoon commented on lesson 5/serhii.karavan/docker-compose.yml
> +    restart: always
`restart: always` робить щоб при перезавантаженні лінукса, цей контейнер автоматично запускався(а всі інші ні). Треба видалити цю опцію.

2020-11-24 09:41 UTC, Karavan89 commented
Lesson 5 fix

2020-11-24 19:04 UTC, MrCartoon commented
Я видалив `server.rb`, тепер ти маєш зробити так щоб воно працювало, копіювати файл не можна.
(Для того щоб отримати останні зміни треба написати `git pull origin master`)

2020-11-25 11:28 UTC, MrCartoon approved these changes

2020-11-25 11:28 UTC, merged