Lesson 5
MastersAcademy/devops-course-2020 pull request #34
Opened 2020-11-24 17:19 UTC by vlad-volkov

2020-11-24 19:12 UTC, MrCartoon requested changes

2020-11-24 19:12 UTC, MrCartoon commented on lesson 5/vladyslav.volkov/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Треба зробити без клонування `server.rb` в свою папку, можеш почитати про [build context](https://docs.docker.com/compose/compose-file/#context), або зробити через [volume](https://docs.docker.com/compose/compose-file/#volumes).

2020-11-26 11:10 UTC, vlad-volkov commented on lesson 5/vladyslav.volkov/server.rb
> +raise unless RUBY_VERSION == '2.6.0'
Зробив

2020-11-26 12:44 UTC, MrCartoon approved these changes

2020-11-26 12:44 UTC, merged