alexey.boguslavets
MastersAcademy/devops-course-2020 pull request #5
Opened 2020-11-08 12:20 UTC by alexxck

help me please with db & cache error

2020-11-08 16:30 UTC, MrCartoon requested changes

2020-11-08 16:30 UTC, MrCartoon commented on lesson 3/alexey.boguslavets/project.sh
> +docker run --rm -d --net ${NETWORK} -p 6379:6379 --name alex_redis redis:4-alpine
Не виконана умова "Извне доступ должен быть только к вебсерверу руби через 9000 порт(сам руби открывает 4567)"

2020-11-08 16:44 UTC, alexxck commented
убрал NAT

2020-11-09 10:20 UTC, MrCartoon approved these changes

2020-11-09 10:20 UTC, merged